services:
  alerting_service:
    build: .
    image: ghcr.io/voltcast-a-ase-project/alerting_service/alert-ms:latest
    container_name: alerting_service
    ports:
      - "8087:8087"
    volumes:
      - sqlite_data:/app/data
    environment:
      - DATABASE_URL=sqlite:////app/data/alerting.db
      - RESEND_API_KEY=${RESEND_API_KEY}
    restart: unless-stopped
    networks:
      - VoltCast_Network

volumes:
  sqlite_data:

networks:
  VoltCast_Network:
    external: true
